# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.11.0
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: CockroachDB database template 🪳
reponame: template-database-cockroach
repourl: https://github.com/radio-aktywne/template-database-cockroach
templatename: cockroach
type: database
